branches:
  only:
    - master

language: php

php:
  - 5.3

before_script:
  - "mysql -e 'create database fluxbb__test;'"
  - "psql -c 'create database fluxbb__test;' -U postgres"

script: phpunit --bootstrap tests/bootstrap_example.php tests/

notifications:
  irc:
    - "irc.freenode.org#fluxbb"
