branches:
  only:
    - master

language: php

php:
  - 5.3

env:
  - DB_MYSQL_DBNAME=fluxbb_test
  - DB_MYSQL_HOST=0.0.0.0
  - DB_MYSQL_USER=
  - DB_MYSQL_PASSWD=
  - DB_SQLITE_DBNAME=:memory:
  - DB_PGSQL_DBNAME=fluxbb_test
  - DB_PGSQL_HOST=127.0.0.1
  - DB_PGSQL_USER=postgres
  - DB_PGSQL_PASSWD=

before_script:
  - "mysql -e 'create database fluxbb__test;'"
  - "psql -c 'create database fluxbb__test;' -U postgres"

script: phpunit tests/

notifications:
  irc:
    - "irc.freenode.org#fluxbb"
